### ISSUE TITLE
aws_iam_role_policy_attachment.secrets_manager_attachment Causes Error

### ISSUE THREAD

**Issue by ethanharmonCWB** [opszero/terraform-aws-kubespot#428] opened 2024-10-29 15:05 UTC
Hey there,

The latest commit to this module has resulted in our infra attempting to create a `aws_iam_role_policy_attachment.secrets_manager_attachment` resource, which results in the error in the attached screenshot. Since this resource is implicitly defined, I have no idea what the value of `roleName` is supposed to be. Is there a way for me to not have this resource be created, or to roll back to a specific version of this module? We have a project that depends on this module that has a go-live date of Oct. 30th and this is a huge blocker.

![image](https://github.com/user-attachments/assets/ec0b47a8-12a6-4246-a42f-53dda7746bf4)

**Comment by ethanharmonCWB** [comment] 2024-10-29 15:11
@abhiyerra @sohanyadav

**Comment by ethanharmonCWB** [comment] 2024-10-29 15:51
Okay I was successfully able to pin a specific version so crisis averted! I'm going to leave this open as a bug report though :)

**Comment by villagab4** [comment] 2024-11-06 14:44
Courtesy of my debugging with Cursor

# Root Cause Analysis: IAM Role Policy Attachment Error in CSI Secrets Store

## Issue
The `aws_iam_role_policy_attachment.secrets_manager_attachment` resource in `aws_csi_secrets_store.tf` fails with a validation error when attempting to create IAM role policy attachments.

## Error Message

```Error: attaching IAM Policy () to IAM Role (): operation error IAM: AttachRolePolicy, https response error StatusCode: 400, RequestID: 977d6d69-d618-4cdf-9a69-edbf0500ccb8, api error ValidationError: The specified value for roleName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@-```

## Root Cause
1. The `aws_iam_role_policy_attachment` resource is missing the `count` parameter that exists on its related resources:
   - `aws_iam_role.secrets_manager_role` has `count = var.csi_secrets_store_enabled ? 1 : 0`
   - `aws_iam_policy.secrets_policy` has `count = var.csi_secrets_store_enabled ? 1 : 0`
   
2. Current problematic code:

```
terraform
resource "aws_iam_role_policy_attachment" "secrets_manager_attachment" {
role = join("",aws_iam_role.secrets_manager_role..name)
policy_arn = join ("", aws_iam_policy.secrets_policy..arn)
}
```

3. The `join()` function is being used unnecessarily and can result in empty strings when the resources aren't created (when `csi_secrets_store_enabled = false`)

## Proposed Fix

```
terraform
resource "aws_iam_role_policy_attachment" "secrets_manager_attachment" {
count = var.csi_secrets_store_enabled ? 1 : 0
role = aws_iam_role.secrets_manager_role[0].name
policy_arn = aws_iam_policy.secrets_policy[0].arn
}
```

## Impact of Fix
1. Adds consistent count parameter to match related resources
2. Properly references the indexed resources when they exist
3. Prevents attempt to create attachment with empty values when feature is disabled
4. Maintains proper dependency chain between resources

## Testing Steps
1. Set `csi_secrets_store_enabled = false` - Should skip creation of all related resources
2. Set `csi_secrets_store_enabled = true` - Should properly create role, policy, and attachment

**Comment by villagab4** [comment] 2024-11-06 14:44
@abhiyerra @ethanharmonCWB @sohanyadav

**Comment by abhiyerra** [comment] 2024-11-07 17:05
Was resolved in: https://github.com/opszero/terraform-aws-kubespot/pull/432

**Closed by abhiyerra** 2024-11-07 17:05 UTC
